Warfork-MVP:
  org: PowderedSong-of-Violet-Skies
  project: 3
  inbox: Inbox
  labels:
    "P0": "Critical"
    "P1": "High"
    "P2": "Medium"
    "P3": "Low"
    "mvp": "MVP"
    "post-mvp": "Post-MVP"
