- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#D4AF37"
  weight: 100
  roles:
    - LordCaptain
    - FirstOfficer
    - MasterOfVox
    - ChoirMasterTelepathica
    - ShipConfessor
    - MasterHelmsman
    - Boatswain
- type: department
  id: Provost
  name: department-Provost
  description: department-Provost-description
  color: "#DE3A3A"
  weight: 90
  roles:
    - ProvostMarshal
    - Commissar
    - Arbitrator
    - ArmsmanSergeant
    - Armsman
    - Warden
- type: department
  id: Enginarium
  name: department-Enginarium
  description: department-Enginarium-description
  color: "#EFB341"
  weight: 80
  roles:
    - MagosEnginseer
    - TechPriestEnginseer
    - Lexmechanic
    - FabricatorAdept
    - ServitorHandler
- type: department
  id: Apothecarion
  name: department-Apothecarion
  description: department-Apothecarion-description
  color: "#52B4E9"
  weight: 70
  roles:
    - ChiefChirurgeon
    - SeniorMedicae
    - ApothecarionAdept
    - Orderly
    - MortisCustodian
- type: department
  id: Archivum
  name: department-Archivum
  description: department-Archivum-description
  color: "#D381C9"
  weight: 60
  roles:
    - MagosBiologis
    - ExploratorAdept
    - Xenologis
    - Cryptologos
- type: department
  id: Munitorum
  name: department-Munitorum
  description: department-Munitorum-description
  color: "#A46106"
  weight: 50
  roles:
    - Quartermaster
    - MunitorumOfficer
    - CargoTech
- type: department
  id: FlightDeck
  name: department-FlightDeck
  description: department-FlightDeck-description
  color: "#7FA8BE"
  weight: 40
  roles:
    - DeckChief
    - ValkyriePilot
    - CrewChief
    - DoorGunner
- type: department
  id: Ministorum
  name: department-Ministorum
  description: department-Ministorum-description
  color: "#9FED58"
  weight: 30
  roles:
    - SeniorConfessor
    - GalleyMaster
    - Remembrancer
    - Steward
    - SanitationCustos
- type: department
  id: ShipCompany
  name: department-ShipCompany
  description: department-ShipCompany-description
  color: "#C0C0C0"
  weight: 20
  roles:
    - Crewman
    - PenalLegionnaire
